name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        os: [ubuntu-latest]

    steps:
      - uses: "actions/checkout@v5"
      - uses: "actions/setup-python@v5.3.0"
        with:
            python-version: "${{ matrix.python-version }}"
      - name: Run CI tests
        run: bash test.sh
        shell: bash
